export const ROUTE_PATHS = {
  ROOT: '/',
  SYSTEM: {
    NOT_FOUND: '*',
  },
  AUTH: {
    ROOT: '/auth',
    LOGIN: 'login',
    REGISTER: 'register',
  },
  PUBLIC: {
    PRODUCTS: 'products',
    PRODUCT_DETAIL: 'product/:slug',
    ABOUT: 'about',
    SEARCH: 'search',
    CONTACT: 'contact',
    FAQ: 'faq',
    TERMS: 'terms',
    PRIVACY: 'privacy',
    REFUND: 'refund',
    CATEGORIES: 'categories',
    CATEGORY_DETAIL: 'category/:slug',
    BECOME_SELLER: 'become-seller',
    COLLECTION: 'collections/:slug',
    TRENDING: 'trending',
    BEST_SELLERS: 'best-sellers',
    NEW_ARRIVALS: 'new-arrivals',
    ON_SALE: 'on-sale',
    WISHLIST: 'wishlist',
    CART: 'cart',
  },
  USER: {
    DASHBOARD: 'user/dashboard',
    ORDERS: 'user/orders',
    CHECKOUT: 'checkout',
    CHECKOUT_SUCCESS: 'checkout/success',
    PROFILE: 'profile',
  },
  SELLER: {
    DASHBOARD: '/seller/dashboard',
    PRODUCTS: '/seller/products',
    EDIT_PRODUCT: '/seller/products/:id/edit',
    UPLOAD: '/seller/upload',
    SALES: '/seller/sales',
    WITHDRAWALS: '/seller/withdrawals',
  },
  ADMIN: {
    ROOT: '/admin',
    USERS: 'users',
    PRODUCTS: 'products',
    PENDING_PRODUCTS: 'products/pending',
    ORDERS: 'orders',
    CATEGORIES: 'categories',
    SELLERS: 'sellers',
  },
};
